# Generated by Django 3.0.1 on 2020-01-20 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UestcStu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuCookies', models.TextField(null=True)),
                ('loginStatus', models.BooleanField(default=False)),
                ('loginHint', models.BooleanField(default=False)),
                ('gradeSpySwitch', models.BooleanField(default=False)),
                ('lastQueryTime', models.DateTimeField()),
                ('belong', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stuInfo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.TextField()),
                ('courseId', models.TextField()),
                ('courseGrade', models.TextField()),
                ('coursePoint', models.TextField(default=0)),
                ('belong', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
