# Generated by Django 3.0.1 on 2020-01-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='serverGroup',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serverPingSwitch',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serverPort',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='serverinfo',
            name='serverUrl',
            field=models.TextField(null=True),
        ),
    ]
