# Generated by Django 3.0.1 on 2020-01-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcserver', '0002_auto_20200121_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverinfo',
            name='serverGroup',
            field=models.IntegerField(null=True),
        ),
    ]
